<?php
/**
 * Created by PhpStorm.
 * User: mcfatem
 * Date: 12/16/2014
 * Time: 8:19 AM
 *
 * This is the home for IHC defined constants.
 */

// Handle System defines

define('H_OBJECT_PATH', 'https://digital.grinnell.edu/islandora/object/');
define('H_PREFIX', '11084');
define('H_ROOTDIR', '/hs');
define('H_SVRDIR', '/hs/srv_1');
define('H_BINDIR', '/hs/hsj-7.1/bin');
define('H_BATCH', 'idu_handle_batch.bat');
define('H_LOG', 'idu_handle_batch.log');
define('H_ADMKEY', ' ');                   // no key pass-phrase defined
define('H_NUMERIC_ONLY', 'grinnell:');


